config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  resources :products do
    resources :contents
    collection do
      get :search
      get :machine_search
    end
  end
  resources :users, only: [:show]
  resources :machines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/machine.rb
class Machine < ApplicationRecord
  has_many :machine_products
  has_many :products, through: :machine_products
  validates :name, presence: true, uniqueness: true
end

app/models/machine_product.rb
class MachineProduct < ApplicationRecord
  belongs_to :machine
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :contents
  has_many :machine_products
  has_many :machines, through: :machine_products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def create
    content = Content.create(title: content_params[:title], text: content_params[:text], user_id: current_user.id, product_id: content_params[:product_id])
    redirect_to "/products/#{content.product.id}"
  end

  def destroy
    @product = Product.find(params[:id])
    @content = @product.contents.find(params[:product_id])
    @content.destroy
    redirect_to product_path(@product)
  end

private
  def content_params
    params.permit(:title, :text, :product_id)
  end

  def set_content
    @content = Content.find(params[:id])
  end

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController

  def new
    
  end

  def create
    
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @products = Product.includes(:user).order("created_at DESC").page(params[:page]).per(20)
  end

  def new
  end

  def create
    Product.create(machine: product_params[:machine], name: product_params[:name], text: product_params[:text], user_id: current_user.id)
  end

  def destroy
    product = Product.find(params[:id])
    if product.user.id == current_user.id
      product.destroy
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    if current_user.id == product.user.id
      product.update(product_params)
    end
  end

  def show
    @product = Product.find(params[:id])
    @contents = @product.contents.includes(:user).order("created_at desc")
  end

  def search
    @products = Product.where('name LIKE(?)', "%#{params[:keyword]}%").order("created_at desc")
  end

  def machine_search
    @products = Product.where('machine LIKE(?)', "%#{params[:keyword]}%").order("created_at desc")
  end

  private
  def product_params
    params.permit(:machine ,:name, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @products = user.products.page(params[:page]).per(5).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/destroy.html.erb
<h3>
  削除が完了しました。
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsRec</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-wrap">
        <a href="/products" class="top-post"><img src="/img/kohacu.com.png" height="100" width="100"></a>
        <% if user_signed_in? %>
          <ul class="post">
            <li class="post_list">
              <a href="/products/new">製品を作成</a>
            </li>
            <li class="post_list">
              <a href="/users/<%= current_user.id %>">マイページ</a>
            </li>
            <li class="post_list">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="post">
            <li class="post_list">
              <%= link_to "ログイン", new_user_session_path %>
            </li>
            <li class="post_list">
              <%= link_to "user登録", new_user_registration_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="footer-wrap">
        <P>
        jobs-rec.
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        jobs-rec.は、製品を作成する際に記録を残しておき、後日作成した製品の詳細を確認するために作成しました。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        汎用性の高いアプリケーションとして使用したかったので、内容を細かく設定していません。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        使用方法は、まずuser登録してください。登録しないと製品の記録はできません。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        製品を作成のボタンをクリックすれば作成画面へ移動します。記述するのは、機械名、製品名、作成数です。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        作成できたら、top画面に作成した製品の記録が表示されます。作成したuser本人なら、記録の削除や編集ができるようになっています。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        詳細ボタンをクリックすれば、製品の詳細を記録することができます。titleには題名を記述し、textには内容を記録します。詳細の中でも、記録した本人であれば詳細内で作成した内容が削除できるようになっています。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        マイページのボタンをクリックすれば、本人が今まで作成してきた製品一覧が表示されます。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        topページで表示されているuserの名前をクリックすれば、そのuserが作成した製品一覧が表示されます。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        他のuserが作成した製品の詳細は誰でも見れるようになっています。詳細内での記録も誰でもできるようになっていて、注意書きなど自由に作成することができます。
        </p>
      </div>
      <div class="footer-wrap">
        <P>
        記録が多くなってきたら探すのが大変になるので、検索機能を作成しました。機械名での検索と製品名での検索ができます。
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/products/create.html.erb
<div class="product_done">
  <h3>
    製品を作成しました。
  </h3>
  <div class="product_done-return">
    <a href="/products">製品一覧に戻る</a>
  </div>
</div>

app/views/products/destroy.html.erb
<div class="product_done">
  <h3>
    製品の記録を削除しました。
  </h3>
  <div class="product_done-return">
    <a href="/">製品一覧に戻る</a>
  </div>
</div>

app/views/products/edit.html.erb
<%= form_tag("/products/#{@product.id}", method: :patch) do %>
  <div class="product_new">
  <h3 class="product_new-title">
    内容を編集する
  </h3>
  <div class="product_new-box">
    <h4>機械名</h4>
    <input type="text" name="machine" placeholder="機械名を記入" value=<%= @product.machine %> class="product_new-name">
    <h4>製品名</h4>
    <input type="text" name="name" placeholder="作成する製品名を記入" value=<%= @product.name %> class="product_new-text">
    <h4>作成数</h4>
    <input type="text" name="text" placeholder="作成数を記入" value=<%= @product.text %> class="product_new-number">
    <input type="submit" value="編集する" class="product_new-btn">
  </div>
</div>

<% end %>

app/views/products/index.html.erb
<div class="products-wrapper">
  <div class="product-center-wrap">
    <div class="product_index-search-box">
      <h4 class="product_index-search">
        <%= link_to '製品名で検索する', "/products/search", method: :get %>
      </h4>
      <h4 class="product_index-search">
        <%= link_to '機械名で検索する', "/products/machine_search", method: :get %>
      </h4>
    </div>
    <% @products.each do |product| %>
      <div class="product-center-wrap-flex">
        <div class="product-center-wrap_name">
          <h2>機械名:<%= product.machine %></h2>
          <h3>製品名:<%= product.name %></h3>
          <p>作成数:<%= product.text %></p>
        </div>
        <div class="product_list">
          <%= link_to "詳細", "/products/#{product.id}", method: :get %>
          <% if user_signed_in? && current_user.id == product.user_id %>
            <%= link_to "削除する", "/products/#{product.id}", method: :delete %>
            <%= link_to "編集する", "/products/#{product.id}/edit", method: :get %>
          <% end %>
        </div>
        <div class="product_create-days">
          <h4>作成者<a href="/users/<%= product.user.id %>"><%= product.user.nickname %></a></h4>
          <p>作成日<%= product.created_at.to_s(:datetime_jp) %></p>
          <%# <p>更新日</p><%= product.updated_at %>
        </div>
      </div>
    <% end %>
    <%= paginate(@products) %>
  </div>
</div>

app/views/products/machine_search.html.erb
<%= form_tag('/products/machine_search', method: :get) do %>
  <div class="search-wrap">
    <input class="search-box" name="keyword" placeholder="機械名で検索する" type="text" value=""><button type="submit" class="search-box-btn">検索</button>
  </div>
<% end %>
<% @products.each do |product| %>
  <div class="product-center-wrap-flex">
    <div class="product-center-wrap_name">
      <h2>機械名:<%= product.machine %></h2>
      <h3>製品名:<%= product.name %></h3>
      <p>作成数:<%= product.text %></p>
    </div>
    <div class="product_list">
      <%= link_to "詳細", "/products/#{product.id}", method: :get %>
      <% if user_signed_in? && current_user.id == product.user_id %>
        <%= link_to "削除する", "/products/#{product.id}", method: :delete %>
        <%= link_to "編集する", "/products/#{product.id}/edit", method: :get %>
      <% end %>
    </div>
    <div class="product_create-days">
      <h4>作成者<a href="/users/<%= product.user.id %>"><%= product.user.nickname %></a></h4>
      <p>作成日<%= product.created_at.to_s(:datetime_jp) %></p>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<%= form_tag('/products', method: :post) do %>
<div class="product_new">
  <h3 class="product_new-title">
    製品を作成する
  </h3>
  <div class="product_new-box">
    <h4>機械名</h4>
    <input type="text" name="machine" placeholder="機械名を記入" class="product_new-name">
    <h4>製品名</h4>
    <input type="text" name="name" placeholder="作成する製品名を記入" class="product_new-text">
    <h4>作成数</h4>
    <input type="text" name="text" placeholder="作成数を記入" class="product_new-number">
    <input type="submit" value="作成する" class="product_new-btn">
  </div>
</div>
<% end %>

app/views/products/search.html.erb
<%= form_tag('/products/search', method: :get) do %>
  <div class="search-wrap">
    <input class="search-box" name="keyword" placeholder="製品名で検索する" type="text" value=""><button type="submit" class="search-box-btn">検索</button>
  </div>
<% end %>
<% @products.each do |product| %>
  <div class="product-center-wrap-flex">
    <div class="product-center-wrap_name">
      <h2>機械名:<%= product.machine %></h2>
      <h3>製品名:<%= product.name %></h3>
      <p>作成数:<%= product.text %></p>
    </div>
    <div class="product_list">
      <%= link_to "詳細", "/products/#{product.id}", method: :get %>
      <% if user_signed_in? && current_user.id == product.user_id %>
        <%= link_to "削除する", "/products/#{product.id}", method: :delete %>
        <%= link_to "編集する", "/products/#{product.id}/edit", method: :get %>
      <% end %>
    </div>
    <div class="product_create-days">
      <h4>作成者<a href="/users/<%= product.user.id %>"><%= product.user.nickname %></a></h4>
      <p>作成日<%= product.created_at.to_s(:datetime_jp) %></p>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="product-center-wrap-flex-content">
  <div class="product-center-wrap_name">
    <h2>機械名:<%= @product.machine %></h2>
    <h3>製品名:<%= @product.name %></h3>
    <p>作成数:<%= @product.text %></p>
  </div>
  <div class="product_create-days">
    <h4>作成者<a href="/users/<%= @product.user.id %>"><%= @product.user.nickname %></a></h4>
  </div>

  <% if user_signed_in? && current_user.id == @product.user_id %>
    <div class="product_list">
      <%= link_to "削除する", "/products/#{@product.id}", method: :delete %>
      <%= link_to "編集する", "/products/#{@product.id}/edit", method: :get %>
    </div>
  <% end %>


  <% if current_user %>
    <%= form_tag("/products/#{@product.id}/contents", method: :post) do %>
      <div class="product_show-content-form">
        <h4>title</h4>
        <input type="text" name="title" placeholder="タイトルを記入する" class="product_show-title">
        <h4>text</h4>
        <textarea name="text" placeholder="テキストを記入する" class="product_show-text"></textarea>
        <input type="submit" value="保存する" class="product_show-submit">
      </div>
    <% end %>
  <% end %>
  <h4 class="product_show-content-title">製品詳細</h4>
  <% if @contents %>
    <% @contents.each do |content| %>
      <div class="product_show-content-list">
        <h2><strong><%= link_to content.user.nickname, "/users/#{content.user_id}" %></strong></h2>
        <h3><%= content.title %></h3>
        <%= simple_format(content.text) %>
        <% if user_signed_in? && current_user.id == content.user_id %>        
          <h4><%= link_to "削除", product_content_path(content.id, content.product_id), method: :delete, data: { confirm: '削除しますか？' } %></h4>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/update.html.erb
<div class="product_done">
  <h3>
    製品の記録を更新しました。
  </h3>
  <div class="product_done-return">
    <a href="/">製品一覧に戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<h2 class="user_show-title"><%= @nickname %>さんの制作した製品一覧</h2>
  <% @products.each do |product| %>
    <div class="product-center-wrap-flex">
      <div class="product-center-wrap_name">
        <h2>機械名:<%= product.machine %></h2>
        <h3>製品名:<%= product.name %></h3>
        <p>作成数:<%= product.text %></p>
      </div>
      <div class="product_list">
        <%= link_to "詳細", "/products/#{product.id}", method: :get %>
        <% if user_signed_in? && current_user.id == product.user_id %>
          <%= link_to "削除する", "/products/#{product.id}", method: :delete %>
          <%= link_to "編集する", "/products/#{product.id}/edit", method: :get %>
        <% end %>
        
        <p class="product_list-day">作成日<%= product.created_at.to_s(:datetime_jp) %></p>
      </div>
  </div>
  <% end %>
<%= paginate(@products) %>